### PR TITLE
Add waifu2x-ncnn-vulkan

### PR DESCRIPTION
**Pull request by CyFeng16**
Since PR #15 is still in draft state, I pulled the PR then established this new branch. Daniel made huge progress that added the waifu2x function to our repository, I just can not wait to complete some follow-up documentation work.
@EtianAM PHAL.

### CODE REVIEW

**Comment by CyFeng16** [comment]
@EtianAM Some conflicts were solved and this PR is ready. Maybe you can give it a go.

**Comment by re2cc** [comment]
Thanks for completing it, I've been a little busy and I couldn't make any progress. I think there's a missing argument, I didn't see it until yesterday, I think it's -x or something like that, I'm not sure, you can see the original arguments with ./waifu2x-ncnn-vulkan in the build folder.
Also missing the extension support (Only supports png)

**Comment by CyFeng16** [comment]
I will try to do something about the missing argument as well as the png output format. Maybe just after a little rest and then I can do the job. What's a pity, rocket didn't launch today (T＿T)

**Comment by CyFeng16** [comment]
@EtianAM I found `-x` for TTA mode and will get it done. The original output format is limited to `png` so that I will obey the rule.
Done!

**Comment by re2cc** [comment]
> @EtianAM I found `-x` for TTA mode and will get it done. The original output format is limited to `png` so that I will obey the rule.
> Done!

Thank you for adding the argument. Hmm... I could swear I've ever given you a jpg input, maybe later I'll check

**Comment by CyFeng16** [comment]
@EtianAM Maybe I misunderstand that. Currently, we input a jpg/png, and then the program outputs a png image.

**Comment by re2cc** [comment]
> @EtianAM Maybe I misunderstand that. Currently, we input a jpg/png, and then the program outputs a png image.

No, I think I should have tried that before I spoke, sorry. Well, I do not see any problems anymore, if I had to give some, it would be that it does not detect errors, that is, if something fails, the script does not warn.
Also that the README of waifu2x-vulkan, has no images, but it is not a big problem, I think that the above could be a little bigger, but neither is something vital.

**Thank you for your work.**

**Comment by CyFeng16** [comment]
We do have a image for description (speeded up through cdn ), which will be seen after merge. We could add some assert judgments if really necessary in another PR.

**Pull request merged**
